// backend/src/model/businessprocess.ts
import mongoose from "mongoose";

const bpSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: { type: String },
    priority: {
      type: String,
      enum: ["Critical", "High", "Medium", "Low"],
      default: "Medium",
    },
    projectId: { type: mongoose.Schema.Types.ObjectId, ref: "Project" },

    // NEW fields for regenerate/matching
    matched: { type: Boolean, default: false, index: true },
    selected: { type: Boolean, default: false, index: true },
    edited: { type: Boolean, default: false, index: true },
    testRunSuccess: { type: Boolean, default: false, index: true },
    score: { type: Number, default: 0 }, // normalized score (0..1)
    source: { type: String, default: "manual" }, // e.g. "openai", "local_score"

    // Detailed business-process fields (generated by OpenAI)
    processObjective: { type: String, default: "" },
    triggerEvent: { type: String, default: "" },
    primaryActors: { type: String, default: "" },
    keyBusinessSteps: { type: String, default: "" },
    businessRules: { type: String, default: "" },
    upstreamSystems: { type: String, default: "" },
    downstreamSystems: { type: String, default: "" },
    regulatoryImpact: { type: String, default: "" },
    riskControlConsiderations: { type: String, default: "" },

    // Editable guidance text per detailed row
    processNameGuidance: { type: String, default: "" },
    processObjectiveGuidance: { type: String, default: "" },
    triggerEventGuidance: { type: String, default: "" },
    primaryActorsGuidance: { type: String, default: "" },
    keyBusinessStepsGuidance: { type: String, default: "" },
    businessRulesGuidance: { type: String, default: "" },
    upstreamSystemsGuidance: { type: String, default: "" },
    downstreamSystemsGuidance: { type: String, default: "" },
    regulatoryImpactGuidance: { type: String, default: "" },
    riskControlConsiderationsGuidance: { type: String, default: "" },
  },
  {
    timestamps: true, // createdAt & updatedAt will be managed automatically
    strict: true,
  }
);

export type BusinessProcessDoc = mongoose.InferSchemaType<typeof bpSchema>;
export const BusinessProcess = mongoose.model<BusinessProcessDoc>(
  "BusinessProcess",
  bpSchema,
  "businessProcesses"
);
